# Generated by Django 3.2.4 on 2021-07-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, verbose_name='no')),
                ('title', models.CharField(max_length=32, unique=True)),
                ('pub_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('press', models.CharField(max_length=32)),
            ],
        ),
    ]
